package cookieMonster;

public class FibsCookies {

	public static final int BGOFIBSCookieNull = -2;
	public static final int FIBS_BAD_COOKIE = -1;

	// Implicitly includes CLIP message IDs; in range 1..19; see clip.h

	public static final int FIBS_PreLogin = Clip.CLIP_LAST_CLIP_ID + 1;
	// the ASCII "FIBS" art; etc.
	public static final int FIBS_LoginPrompt=22;
	// use this to detect a failed login (e.g. wrong password):
	public static final int FIBS_FailedLogin=23;
    // Registration cookies
	public static final int BGOFIBSCookieGuestWelcome=24;
	public static final int BGOFIBSCookieGuestPrompt=25;
	public static final int BGOFIBSCookieUserNameInUse=26;
	public static final int BGOFIBSCookieInvalidUserName=27;
	public static final int BGOFIBSCookieTypeInNoPassword=28;
	public static final int BGOFIBSCookiePasswordPrompt=29;
	public static final int BGOFIBSCookieInvalidPassword=30;
	public static final int BGOFIBSCookieRetypePasswordPrompt=31;
	public static final int BGOFIBSCookiePasswordsNotIdentical=32;
	public static final int BGOFIBSCookieUserNameRegistered=33;
	public static final int BGOFIBSCookieWelcomeBack=34;
	public static final int BGOFIBSCookieNotAway=35;
	public static final int FIBS_MOTD=36;
	public static final int FIBS_Goodbye=37;
	public static final int FIBS_PostGoodbye=38;	// "send cookies"; etc.
	public static final int FIBS_Unknown=39;	// don't know the type; probably can ignore
	public static final int FIBS_Empty=40;	// empty string
	public static final int FIBS_Junk=41;	// a message we don't care about; but is not unknown
	public static final int FIBS_ClearScreen=42;
	// DANGER; WILL ROBINSON!!! See notes in .c file about these three cookies! // MODIFIED
	public static final int BGOFIBSCookieYouAcceptDoubleBad=43;
	public static final int FIBS_BAD_AcceptDouble=44;
	public static final int FIBS_BAD_Board=45;
	public static final int FIBS_Average=46; // int value = 46
	public static final int FIBS_DiceTest=47;
	public static final int FIBS_Stat=48;
	public static final int FIBS_Why=49;
	public static final int FIBS_NoInfo=50;
	public static final int FIBS_LastLogout=51; // int value 51
	public static final int FIBS_RatingCalcStart=52;
	public static final int FIBS_RatingCalcInfo=53;
	public static final int FIBS_SettingsHeader=54;
	public static final int FIBS_PlayerListHeader=55;
	public static final int FIBS_AwayListHeader=56;
	public static final int FIBS_RatingExperience=57;
	public static final int FIBS_NotLoggedIn=58;
	public static final int FIBS_StillLoggedIn=59;
	public static final int FIBS_NoOneIsAway=60;
	public static final int FIBS_RatingsHeader=61; // int value 61
	public static final int FIBS_IsPlayingWith=62;
	public static final int FIBS_Timeout=63;
	public static final int FIBS_UnknownCommand=64;
	public static final int FIBS_Username=65;
	public static final int FIBS_LastLogin=66;
	public static final int FIBS_YourLastLogin=67;
	public static final int FIBS_Registered=68;
	public static final int FIBS_ONEUSERNAME=69;
	public static final int FIBS_EnterUsername=70;
	public static final int FIBS_EnterPassword=71; // int value 71
	public static final int FIBS_TypeInNo=72;
	public static final int FIBS_SavedScoreHeader=73;
	public static final int FIBS_NoSavedGames=74;
	public static final int IBS_UsersHeardYou=75;
	public static final int FIBS_MessagesForYou=76;
	public static final int FIBS_IsAway=77;
	public static final int BGOFIBSCookieOpponentDrops=78;
	public static final int FIBS_OpponentLogsOut=79;
	public static final int FIBS_Waves=80;
	public static final int FIBS_WavesAgain=81; // int value 81
	public static final int FIBS_YouGag=82;
	public static final int FIBS_YouUngag=83;
	public static final int FIBS_YouBlind=84;
	public static final int FIBS_YouUnblind=85;
	public static final int FIBS_WatchResign=86;
	public static final int FIBS_UseToggleReady=87;
	public static final int FIBS_WARNINGSavedMatch=88;
	public static final int FIBS_NoSavedMatch=89;
	public static final int FIBS_AlreadyPlaying=90;
	public static final int FIBS_DidntInvite=91; // int value 91
	public static final int FIBS_WatchingHeader=92;
	public static final int FIBS_NotWatching=93;
	public static final int FIBS_NotWatchingPlaying=94;
	public static final int FIBS_NotPlaying=95;
	public static final int BGOFIBSCookieNotPlayingSoYouCantGiveUp=96;
	public static final int BGOFIBSCookiePlayerDidntDoubleOrResign=97;
	public static final int FIBS_PlayerNotPlaying=98;
	public static final int FIBS_NoUser=99;
	public static final int FIBS_CantInviteSelf=100;
	public static final int FIBS_CantWatch=101; // int value 101
	public static final int FIBS_CantTalk=102;
	public static final int FIBS_CantBlindYourself=103;
	public static final int BGOFIBSCookieShoutingDisabled=104;
	public static final int BGOFIBSCookieNetworkError=105;
	public static final int FIBS_CantGagYourself=106;
	public static final int FIBS_WontListen=107;
	public static final int BGOFIBSCookieSayToYourself=108;
	public static final int FIBS_TypeBack=109;
	public static final int FIBS_NoOne=110;
	public static final int FIBS_BadMove=111; // int value 111
	public static final int FIBS_MustMove=112;
	public static final int BGOFIBSCookieDontGiveMore=113;
	public static final int FIBS_MustComeIn=114;
	public static final int FIBS_CantShout=115;
	public static final int FIBS_DontKnowUser=116;
	public static final int FIBS_MessageUsage=117;
	public static final int FIBS_Done=118;
	public static final int FIBS_SavedMatchesHeader=119;
	public static final int FIBS_NotYourTurnToRoll=120;
	public static final int FIBS_NotYourTurnToMove=121; // int value 121
	public static final int BGOFIBSCookieNotYourTurnToDouble=122;
	public static final int BGOFIBSCookieRollDiceBeforeMove=123;
	public static final int BGOFIBSCookieIllegalMoveCommand=124;
	public static final int FIBS_YourTurnToMove=125;
	public static final int FIBS_Ratings=126;
	public static final int FIBS_PlayerInfoStart=127;
	public static final int FIBS_EmailAddress=128;
	public static final int FIBS_NoEmail=129;
	public static final int FIBS_ListOfGames=130;
	public static final int FIBS_SavedMatch=131; // int value 131
	public static final int FIBS_SavedMatchPlaying=132;
	public static final int FIBS_SavedMatchReady=133;
	public static final int FIBS_YouAreWatching=134;
	public static final int FIBS_YouStopWatching=135;
	public static final int BGOFIBSCookieBannedFromWatching=136;
	public static final int FIBS_PlayerStartsWatching=137;
	public static final int FIBS_PlayerStopsWatching=138;
	public static final int FIBS_PlayerIsWatching=139;
	public static final int FIBS_ReportUnlimitedMatch=140;
	public static final int FIBS_ReportLimitedMatch=141; // int value 141
	public static final int FIBS_RollOrDouble=142;
	public static final int FIBS_YouWinMatch=143;
	public static final int FIBS_PlayerWinsMatch=144;
	public static final int FIBS_YouReject=145;
	public static final int FIBS_YouResign=146;
	public static final int FIBS_ResumeMatchRequest=147;
	public static final int FIBS_ResumeMatchAck0=148;
	public static final int FIBS_ResumeMatchAck5=149;
	public static final int FIBS_NewMatchRequest=150;
	public static final int FIBS_UnlimitedInvite=151; // int value 151
	public static final int FIBS_YouInvited=152;
	public static final int FIBS_NewMatchAck9=153;
	public static final int FIBS_NewMatchAck10=154;
	public static final int FIBS_NewMatchAck2=155;
	public static final int FIBS_YouTerminated=156;
	public static final int BGOFIBSCookieNoOneToLeave=157;
	public static final int FIBS_OpponentLeftGame=158;
	public static final int FIBS_PlayerLeftGame=159;
	public static final int FIBS_PlayerRefusingGames=160;
	public static final int FIBS_TypeJoin=161; // int value 161
	public static final int FIBS_ShowMovesStart=162;
	public static final int FIBS_ShowMovesWins=163;
	public static final int FIBS_ShowMovesRoll=164;
	public static final int FIBS_ShowMovesDoubles=165;
	public static final int FIBS_ShowMovesAccepts=166;
	public static final int FIBS_ShowMovesRejects=167;
	public static final int BGOFIBSCookieOldmovesWantsToResign=168;
	public static final int FIBS_ShowMovesOther=169;
	public static final int FIBS_Board=170;
	public static final int FIBS_YouRoll=171; // int value 171
	public static final int FIBS_PlayerRolls=172;
	public static final int FIBS_PlayerMoves=173;
	public static final int FIBS_Doubles=174;
	public static final int FIBS_AcceptRejectDouble=175;
	public static final int FIBS_StartingNewGame=176;
	public static final int FIBS_PlayerAcceptsDouble=177;
	public static final int BGOFIBSCookieWatchedPlayerAcceptsDouble=178;
	public static final int FIBS_YouAcceptDouble=179;
	public static final int FIBS_Settings=180;
	public static final int FIBS_Turn=181; // int value 181
	public static final int FIBS_FirstRoll=182;
	public static final int FIBS_DoublingCubeNow=183;
	public static final int FIBS_CantMove=184;
	public static final int FIBS_CantMoveFirstMove=185;
	public static final int FIBS_ResignRefused=186;
	public static final int BGOFIBSCookieYouWinGameWithOldmovesScoreUpdate=187;
	public static final int FIBS_YouWinGame=188;
	public static final int FIBS_OnlyPossibleMove=189;
	public static final int BGOFIBSCookieAcceptWinsWithOldmovesScoreUpdate=190;
	public static final int FIBS_AcceptWins=191;
	public static final int FIBS_ResignWins=192;
	public static final int BGOFIBSCookieResignYouWinWithOldmovesScoreUpdate=193;
	public static final int FIBS_ResignYouWin=194;
	public static final int FIBS_WatchGameWins=195;
	public static final int FIBS_ScoreUpdate=196;
	public static final int BGOFIBSCookieOldmovesMatchStart=197;
	public static final int BGOFIBSCookieOldmovesUnlimitedMatchStart=198;
	public static final int BGOFIBSCookieYouAcceptAndWinWithOldmovesScoreUpdate=199;
	public static final int FIBS_YouAcceptAndWin=200;
	public static final int FIBS_OnlyMove=201;
	public static final int FIBS_BearingOff=202;
	public static final int FIBS_PleaseMove=203;
	public static final int FIBS_MakesFirstMove=204;
	public static final int FIBS_YouDouble=205;
	public static final int FIBS_MatchLength=206;
	public static final int FIBS_PlayerWantsToResign=207;
	public static final int BGOFIBSCookiePlayerWinsGameWithOldmovesScoreUpdate=208;
	public static final int FIBS_PlayerWinsGame=209;
	public static final int BGOFIBSCookieWatchedPlayerWinsGame=210;
	public static final int FIBS_JoinNextGame=211;
	public static final int FIBS_ResumingUnlimitedMatch=212;
	public static final int FIBS_ResumingLimitedMatch=213;
	public static final int FIBS_PlayersStartingMatch=214;
	public static final int FIBS_PlayersStartingUnlimitedMatch=215;
	public static final int FIBS_MatchResult=216;
	public static final int BGOFIBSCookieYouGiveUpWithOldmovesScoreUpdate=217;
	public static final int FIBS_YouGiveUp=218;
	public static final int FIBS_PlayerIsWaitingForYou=219;
	public static final int FIBS_Boardstyle=220;
	public static final int FIBS_Linelength=221;
	public static final int FIBS_Pagelength=222;
	public static final int FIBS_Redoubles=223;
	public static final int FIBS_Sortwho=224;
	public static final int FIBS_Timezone=225;
	public static final int FIBS_RedoublesSetTo=226;
	public static final int BGOFIBSCookieSortWhoValue=227;
	public static final int BGOFIBSCookieSortWhoValueSetTo=228;
	public static final int BGOFIBSCookieSortWhoValueInvalid=229;
	public static final int BGOFIBSCookieBoardStyleValue=230;
	public static final int BGOFIBSCookieBoardStyleValueSetTo=231;
	public static final int BGOFIBSCookieBoardStyleValueInvalid=232;
	
	
	// Pipcounts
	public static final int BGOFIBSCookiePipCount=233;
	public static final int BGOFIBSCookiePlayerDoesntAllowPip=234;
	public static final int BGOFIBSCookieTypeAllowPipFirst=235;
	public static final int BGOFIBSCookiePlayersDontAllowPipCounts=236; // Differs from clip spec; see .m
	public static final int BGOFIBSCookieWaitUntilAcceptReject=237;
	public static final int BGOFIBSCookieBADBearingOff=238;
	public static final int BGOFIBSCookieSavedCount=239;
	public static final int BGOFIBSCookieSavedCountZero=240;
	public static final int BGOFIBSCookieJoinWho=241;
	public static final int BGOFIBSCookieSavedMatchCorrupt=242;
	public static final int BGOFIBSCookieCantPlayTwoGames=243;
	public static final int BGOFIBSCookieInviteWho=244;
	public static final int BGOFIBSCookieNotExperiencedEnough=245;
	public static final int BGOFIBSCookieYouAreAlreadyPlaying=246;
	public static final int BGOFIBSCookieYouAlreadyDidThat=247;
	public static final int BGOFIBSCookieYouDidAlreadyRoll=248;
	public static final int BGOFIBSCookieYouCanOnlyDouble=249;
	public static final int BGOFIBSCookieWaitUntilMoved=250;
	public static final int BGOFIBSCookieWaitForLastInvitation=251;
	public static final int BGOFIBSCookieRedoublesSetToNone=252;
	public static final int BGOFIBSCookieRedoublesSetToUnlimited=253;
	public static final int BGOFIBSCookieNotPlayingWatching=254;
	public static final int BGOFIBSCookieStarsUnknown=255;
	public static final int BGOFIBSCookieWantedToResign=256;
	public static final int BGOFIBSCookieDoesntWantYouToWatch=257;
	public static final int BGOFIBSCookieWatchWho=258;
	public static final int BGOFIBSCookieMirror=259;
	public static final int BGOFIBSCookieJoinedUnlimitedMatch=260;
	public static final int BGOFIBSCookieSavedUnlimitedMatch=261;
	public static final int BGOFIBSCookieSavedUnlimitedMatchPlaying=262;
	public static final int BGOFIBSCookieSavedUnlimitedMatchReady=263;
	public static final int BGOFIBSCookieScoreUpdateUnlimited=264;
	public static final int BGOFIBSCookieNowAllowedToCreateNewGames=265;
	public static final int BGOFIBSCookieUserNameTooLong=266;
	public static final int FIBS_LastMessage=267;
	
	// Boolean settings
	// have to see, what these things mean and how they are used
	public static boolean FIBS_Allowpip=true;
	public static boolean FIBS_Autoboard=true;
	public static boolean FIBS_Autodouble=false;
	public static boolean FIBS_Automove=true;
	public static boolean FIBS_Bell=true;
	public static boolean FIBS_Crawford=false;
	public static boolean FIBS_Double=false;
	public static boolean FIBS_Moreboards=false;
	public static boolean FIBS_Moves=false;
	public static boolean FIBS_Greedy=true;
	public static boolean FIBS_Notify=true;
	public static boolean FIBS_RatingsBool=true;
	public static boolean FIBS_Ready=true;
	public static boolean FIBS_Report=true;
	public static boolean FIBS_Silent=false;
	public static boolean FIBS_Telnet=true;
	public static boolean FIBS_Wrap=false;
}
